### ISSUE TITLE
TODO: publish to crates.io

### ISSUE THREAD

**Issue by akavel** [akavel/care#17]
- [x] reserve `care` crate
- [x] `effectors` - add prefix; workspacify; add license & desc; test care build; publish
- [x] `f-lua` - add prefix; workspacify; add license & desc; test care build; publish
- [x] `f-scp` - add prefix; workspacify; add license & desc; test care build; publish
- [x] `f-zeroinstall` - add prefix; workspacify; add license & desc; test care build; publish
- [x] `parse_ncl` - add prefix; workspacify; add license & desc; test care build; publish
- [x] `script` - add prefix; workspacify; add license & desc; test care build; publish
- [x] main - add license & desc; test care build; publish
- [x] rename repo
- [x] update repo desc
